name: TownyAntiTrap
version: '${project.version}'
main: me.stoffeh.townyantitrap.TownyAntiTrap
api-version: '1.20'
description: A plugin that adds inventory protection when teleporting into a town. Removes the spawn trapping aspect of Towny.
author: StoffeH